### ISSUE TITLE
Segfault when window is manually resized to very small sizes

### ISSUE THREAD

**Issue by KrolPolski** [KrolPolski/cube3D#34]
If you resize the cub3d window to a very small size, a segfault occurs.
```
 rboudwin@Isildur:~/repos/cube3d-minty-freshness$ ./cub3D maps/valid/bigger.cub 
AddressSanitizer:DEADLYSIGNAL
=================================================================
==8666==ERROR: AddressSanitizer: SEGV on unknown address 0x622400005d7c (pc 0x55631afe92d6 bp 0x7ffd316fb140 sp 0x7ffd316fb108 T0)
==8666==The signal is caused by a WRITE memory access.
    #0 0x55631afe92d6 in mlx_draw_pixel (/home/rboudwin/repos/cube3d-minty-freshness/cub3D+0xe72d6) (BuildId: ebc5b68c593f77efa4ee67a0bf998b27e91d54e3)
    #1 0x55631afe1b67 in draw_2d_player (/home/rboudwin/repos/cube3d-minty-freshness/cub3D+0xdfb67) (BuildId: ebc5b68c593f77efa4ee67a0bf998b27e91d54e3)
    #2 0x55631afe1cc2 in draw_2d_map (/home/rboudwin/repos/cube3d-minty-freshness/cub3D+0xdfcc2) (BuildId: ebc5b68c593f77efa4ee67a0bf998b27e91d54e3)
    #3 0x55631afe4e03 in handle_resize (/home/rboudwin/repos/cube3d-minty-freshness/cub3D+0xe2e03) (BuildId: ebc5b68c593f77efa4ee67a0bf998b27e91d54e3)
    #4 0x7f023d6aecfb  (/lib/x86_64-linux-gnu/libglfw.so.3+0x1ccfb) (BuildId: e4e86cae6c52eff761b9509b8369a74f568229f2)
    #5 0x55631afe9277 in mlx_loop (/home/rboudwin/repos/cube3d-minty-freshness/cub3D+0xe7277) (BuildId: ebc5b68c593f77efa4ee67a0bf998b27e91d54e3)
    #6 0x55631afe502b in setup_mlx (/home/rboudwin/repos/cube3d-minty-freshness/cub3D+0xe302b) (BuildId: ebc5b68c593f77efa4ee67a0bf998b27e91d54e3)
    #7 0x55631afe27d0 in main (/home/rboudwin/repos/cube3d-minty-freshness/cub3D+0xe07d0) (BuildId: ebc5b68c593f77efa4ee67a0bf998b27e91d54e3)
    #8 0x7f023d38bd8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #9 0x7f023d38be3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #10 0x55631af235c4 in _start (/home/rboudwin/repos/cube3d-minty-freshness/cub3D+0x215c4) (BuildId: ebc5b68c593f77efa4ee67a0bf998b27e91d54e3)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/rboudwin/repos/cube3d-minty-freshness/cub3D+0xe72d6) (BuildId: ebc5b68c593f77efa4ee67a0bf998b27e91d54e3) in mlx_draw_pixel
==8666==ABORTING
```
This was observed on my laptop running Linux Mint and has not yet been reproduced on school equipment.

**Comment by KrolPolski** [comment]
The window can be minimized and maximized with no issues, it only is a problem if it is resized to a very small window.

**Comment by KrolPolski** [comment]
Issue is here:

```c
void	draw_2d_player(t_map *map, t_info *info)
{
	int	px_x;
	int	px_y;
	int	i;
	int	k;

	px_x = info->p_x * map->sq; //- 5;
	px_y = info->p_y * map->sq; //- 5;
	i = 0;
	k = 0;
	ft_memset(info->img->plyr->pixels, 0, info->img->plyr->width
		* info->img->plyr->height * BPP);
	while (k < 10)
	{
		while (i < 10)
		{
			mlx_put_pixel(info->img->plyr, px_x + i, px_y + k,
				get_rgba(255, 0, 0, 255));
			i++;
		}
		i = 0;
		k++;
	}
	draw_fov(info, px_x + 5, pxpx_x = info->p_x * map->sq; //- 5;
	px_y = info->p_y * map->sq; //- 5;_y + 5);
}
```
These two lines before read: 
```c
px_x = info->p_x * map->sq - 5;
px_y = info->p_y * map->sq - 5;
```
If the map-sq gets too small the minus 5 becomes a problem and tries to draw outside of the image.
I don't recall why this -5 was there in the first place, do you @ThomasParratt ?
